package com.hb.utils.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hb.utils.modle.login.Token;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOKEN".
*/
public class TokenDao extends AbstractDao<Token, Void> {

    public static final String TABLENAME = "TOKEN";

    /**
     * Properties of entity Token.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TokenCode = new Property(0, String.class, "TokenCode", false, "TOKEN_CODE");
        public final static Property OAuthCode = new Property(1, String.class, "OAuthCode", false, "OAUTH_CODE");
    }


    public TokenDao(DaoConfig config) {
        super(config);
    }
    
    public TokenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOKEN\" (" + //
                "\"TOKEN_CODE\" TEXT," + // 0: TokenCode
                "\"OAUTH_CODE\" TEXT);"); // 1: OAuthCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOKEN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Token entity) {
        stmt.clearBindings();
 
        String TokenCode = entity.getTokenCode();
        if (TokenCode != null) {
            stmt.bindString(1, TokenCode);
        }
 
        String OAuthCode = entity.getOAuthCode();
        if (OAuthCode != null) {
            stmt.bindString(2, OAuthCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Token entity) {
        stmt.clearBindings();
 
        String TokenCode = entity.getTokenCode();
        if (TokenCode != null) {
            stmt.bindString(1, TokenCode);
        }
 
        String OAuthCode = entity.getOAuthCode();
        if (OAuthCode != null) {
            stmt.bindString(2, OAuthCode);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Token readEntity(Cursor cursor, int offset) {
        Token entity = new Token( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // TokenCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // OAuthCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Token entity, int offset) {
        entity.setTokenCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setOAuthCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Token entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Token entity) {
        return null;
    }

    @Override
    public boolean hasKey(Token entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
